<?php
// Project: TestProject
// Generated by Backendo

// Start session
session_start();

// Include database connection
require_once 'config/db.php';
// Include helper functions
require_once 'includes/functions.php';

// Determine the requested page
$page = isset($_GET['page']) ? sanitize_input($_GET['page']) : 'home';

// Include the appropriate controller
switch ($page) {
    case 'home':
        require_once 'controllers/HomeController.php';
        $controller = new HomeController();
        $controller->index();
        break;
    default:
        // Page not found
        header('HTTP/1.0 404 Not Found');
        echo '<h1>404 - Page Not Found</h1>';
        break;
}
