    </main>
    <footer>
        <div class="container">
            <p>&copy; 2025 TestProject. Generated by Backendo.</p>
        </div>
    </footer>
    <script src="assets/js/main.js"></script>
</body>
</html>
